### ISSUE TITLE
cannot find USB Port 

### ISSUE THREAD

**Issue by francose** [Fruity-Grebbles/HAB#6]
Couldn't find a Board on the selected port. Check that you have the correct port selected.  If it is correct, try pressing the board's reset button after initiating the upload.
processing.app.SerialException: Error opening serial port '/dev/cu.usbmodem1421'.
	at processing.app.Serial.<init>(Serial.java:147)
	at processing.app.Serial.<init>(Serial.java:82)
	at processing.app.SerialMonitor$4.<init>(SerialMonitor.java:101)
	at processing.app.SerialMonitor.open(SerialMonitor.java:101)
	at processing.app.AbstractMonitor.resume(AbstractMonitor.java:104)
	at processing.app.Editor.resumeOrCloseSerialMonitor(Editor.java:2218)
	at processing.app.Editor.access$2200(Editor.java:79)
	at processing.app.Editor$DefaultExportHandler.run(Editor.java:2196)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jssc.SerialPortException: Port name - /dev/cu.usbmodem1421; Method name - openPort(); Exception type - Port not found.
	at jssc.SerialPort.openPort(SerialPort.java:167)
	at processing.app.Serial.<init>(Serial.java:136)
	... 8 more
Error opening serial port '/dev/cu.usbmodem1421'.

Error opening serial port '/dev/cu.usbmodem1411'. (Port not found)

**Comment by grebz-dev** [comment]
This is not a code issue, but an Arduino IDE configuration issue.
> Couldn't find a Board on the selected port. Check that you have the correct port selected. If it is correct, try pressing the board's reset button after initiating the upload.
This is more than likely the best course of action.

**Comment by francose** [comment]
void loop() {
 if (Serial.available() ){
     processSyncMessage();
 }else{
    ...random code 
}
